@startuml
'https://plantuml.com/class-diagram
Title cupcakes domænemodel
hide circle
hide methods

class Customer {
name
address
phone number
}

class Order {
Order_id
product_id
total_price
}

class Cupcake {
Bottom
Topping
price

}

class Store {

}



Customer "1" -right- "*" Order: places
Order "*" - "*" Cupcake
Customer -- Store
Order -- Store
Cupcake -- Store


@enduml